package org.dani;

/**
 * MAVEN STANDARD DIRECTORY LAYOUT (Base Architecture)
 * * [Project Root]
 * │
 * ├── pom.xml                : Project Object Model (The "Brain" - holds dependencies,
 * │                            plugins, and build configurations).
 * │
 * ├── src/                   : All source material for the project lives here.
 * │   │
 * │   ├── main/              : Source code and resources that will be part of the
 * │   │   │                    final distributed artifact (JAR/WAR).
 * │   │   │
 * │   │   ├── java/          : Production Java source files (mirrors package structure).
 * │   │   ├── resources/     : Config files, property files, XMLs (copied to classpath).
 * │   │   └── webapp/        : (Optional) Web application resources like CSS, JS, HTML.
 * │   │
 * │   └── test/              : Code and resources strictly for testing. Never
 * │       │                    included in the final production build.
 * │       │
 * │       ├── java/          : Test Java source files (JUnit/TestNG scripts).
 * │       └── resources/     : Test-specific data (JSON files, mock data, test configs).
 * │
 * └── target/                : Generated by Maven. Stores compiled bytecode (.class),
 * reports, and the final packaged JAR/WAR.
 * (Deleted upon 'mvn clean').
 */

public class App
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
